name: "Hostinger Deploy"
description: "A composite GitHub Action to streamline and automate the deployment of your site to Hostinger."
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  source-path:
    description: "Path of the directory containing your site (out, dist, build)"
    required: true
  domain:
    description: "Your domain in Hostinger (example.com)"
    required: true
  host:
    required: true
    description: "Hostinger SSH host"
  port:
    required: true
    description: "Hostinger SSH port"
  username:
    required: true
    description: "Hostinger SSH username"
  password:
    required: true
    description: "Hostinger SSH password"

runs:
  using: composite
  steps:
    - name: Upload to Hostinger
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        port: ${{ inputs.port }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        source: "${{ inputs.source-path }}/*"
        target: "domains/${{ inputs.domain }}/public_html/"
        strip_components: 1